"""initial schema: locations, ingestion_runs, forecast_values

Revision ID: 25bf8541c7d8
Revises: 
Create Date: 2026-09-03 17:18:51.146992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bf8541c7d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_slug'), 'locations', ['slug'], unique=True)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.CheckConstraint("status in ('running', 'success', 'failed')", name='ck_ingestion_runs_status'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_location_scheduled_for', 'ingestion_runs', ['location_id', 'scheduled_for'], unique=False)
    op.create_table('forecast_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.SmallInteger(), nullable=False),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_run_id', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Numeric(), nullable=True),
    sa.Column('precipitation_mm', sa.Numeric(), nullable=True),
    sa.Column('precipitation_probability', sa.SmallInteger(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Numeric(), nullable=True),
    sa.Column('wind_direction_deg', sa.SmallInteger(), nullable=True),
    sa.Column('cloud_cover_pct', sa.SmallInteger(), nullable=True),
    sa.Column('relative_humidity_pct', sa.SmallInteger(), nullable=True),
    sa.Column('weather_code', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'target_time', 'issued_at', name='uq_forecast_values_natural_key')
    )
    op.create_index('ix_forecast_values_issued_at', 'forecast_values', ['issued_at'], unique=False)
    op.create_index('ix_forecast_values_location_target_issued', 'forecast_values', ['location_id', 'target_time', 'issued_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forecast_values_location_target_issued', table_name='forecast_values')
    op.drop_index('ix_forecast_values_issued_at', table_name='forecast_values')
    op.drop_table('forecast_values')
    op.drop_index('ix_ingestion_runs_location_scheduled_for', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_locations_slug'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
